[tool.poetry]
name = "poet"
version = "0.1.0"
description = ""
authors = ["Shakthi <revathijebamani@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
numpy="*"



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
